### ISSUE TITLE
Analytics - Add cron job for Reports Auto-Archiving

### ISSUE THREAD

**Issue by sebastianr6** [ietf-tools/analytics#2]
Analytics needs to run this cron task in order to generate archives.

https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/
```[tasklist]
### Tasks
- [x] Add the cron job to the container init code
- [x] Verify that cron job output goes to central logging infrastructure
- [x] Make sure archive emails are sent
```
